[package]
name = "shove"
version = "0.1.0"
authors = ["declan <awesomeriptide@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
